name: gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node packages
        run: npm install
          
      - name: Build site
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # Pinning for security reasons (action not provided by GitHub)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
